{{
    config(
        materialized='view'
    )
}}

SELECT
    FAM_BT_MOTTAKER.PK_BT_MOTTAKER,
    FAM_BT_MOTTAKER.FK_PERSON1,
    FAM_BT_MOTTAKER.BELOP,
    FAM_BT_MOTTAKER.BELOPHIE,
    FAM_BT_MOTTAKER.SAMBO,
    FAM_BT_MOTTAKER.PROSENT,
    FAM_BT_MOTTAKER.EOKLAND,
    FAM_BT_MOTTAKER.EODLAND,
    FAM_BT_MOTTAKER.EOYBLAND,
    FAM_BT_MOTTAKER.EOPENS,
    FAM_BT_MOTTAKER.EOOBLAND,
    FAM_BT_MOTTAKER.EOMORNAS,
    FAM_BT_MOTTAKER.EOFARNAS,
    FAM_BT_MOTTAKER.EOYBNAS,
    FAM_BT_MOTTAKER.EOKODE,
    FAM_BT_MOTTAKER.SYSTEM,
    FAM_BT_MOTTAKER.TKNR,
    FAM_BT_MOTTAKER.TEKSTK,
    FAM_BT_MOTTAKER.BELOPHIT,
    FAM_BT_MOTTAKER.STATUSK,
    FAM_BT_MOTTAKER.ANTBARN,
    FAM_BT_MOTTAKER.ANTBARNH,
    FAM_BT_MOTTAKER.YBARN,
    FAM_BT_MOTTAKER.KJONN,
    FAM_BT_MOTTAKER.FODSEL_AAR,
    FAM_BT_MOTTAKER.STAT_AARMND,
    FAM_BT_MOTTAKER.FODSEL_MND,
    FAM_BT_MOTTAKER.KILDE,
    FAM_BT_MOTTAKER.BOSTED_KOMMUNE_NR,
    FAM_BT_MOTTAKER.BOSTED_BYDEL_KOMMUNE_NR,
    DIM_GEOGRAFI.Navarende_KOMMUNE_NR,
    --DIM_PERSON.BOSTED_LAND,
    FAM_BT_MOTTAKER.FAGSAK_ID,
    FAM_BT_MOTTAKER.BELOP_UTVIDET,
    FAM_BT_MOTTAKER.BELOPHIT_UTVIDET,
    FAM_BT_MOTTAKER.BELOPE,
	DIM_PERSON.GT_VERDI DIM_GT_VERDI,
 	DIM_PERSON.GETITYPE DIM_GETITYPE,
 	DIM_PERSON.GETITYPE,
    FAM_BT_MOTTAKER.SOKERSAKTIVITET,
    FAM_BT_MOTTAKER.ANNENFORELDER_AKTIVITET,
    FAM_BT_MOTTAKER.KOMPETANSE_RESULTAT,
    FAM_BT_MOTTAKER.BARNETS_BOSTEDSLAND,
    FAM_BT_MOTTAKER.MOTTAKER_BOSTED_LAND,
    FAM_BT_MOTTAKER.FK_DIM_PERSON,
    FAM_BT_MOTTAKER.FK_DIM_ALDER,
    FAM_BT_MOTTAKER.FK_DIM_KJONN,
    FAM_BT_MOTTAKER.FK_DIM_LAND_FODT,
    FAM_BT_MOTTAKER.fk_dim_tid_mnd,
    FAM_BT_MOTTAKER.FK_DIM_GEOGRAFI_BOSTED
FROM
  {{ source('dvh_fam_bt','fam_bt_mottaker') }} fam_bt_mottaker

LEFT OUTER JOIN {{ source('dt_person','dim_person') }} DIM_PERSON ON
FAM_BT_MOTTAKER.FK_DIM_PERSON=DIM_PERSON.PK_DIM_PERSON
--AND FAM_BT_MOTTAKER.FK_DIM_PERSON IS NOT NULL

    LEFT OUTER JOIN {{ source('dt_kodeverk','dim_geografi') }} DIM_GEOGRAFI ON
    FAM_BT_MOTTAKER.FK_DIM_GEOGRAFI_BOSTED=DIM_GEOGRAFI.PK_DIM_GEOGRAFI


WHERE
    FAM_BT_MOTTAKER.STAT_AARMND > 202200
    AND FAM_BT_MOTTAKER.STAT_AARMND < 202300
    AND FAM_BT_MOTTAKER.GYLDIG_FLAGG=1