version: 2

sources:

  - name: fam_bt
    schema: dvh_fam_bt
    tables:
      - name: fam_bt_meta_data
        description: 'inneholder meta_data for barnetrygd'
      - name: fam_bt_fagsak
        description: 'inneholder vedtaks informasjon'