comment on column dvh_fam_bt.fak_bt_mottaker.pk_bt_mottaker is '#NAVN Primærnøkkel #INNHOLD Primær key';
comment on column dvh_fam_bt.fak_bt_mottaker.fk_person1 is '#NAVN FK_PERSON1 #INNHOLD DVH sin identifikator for FNR, mottaker av ytelsen';
comment on column dvh_fam_bt.fak_bt_mottaker.belop is '#NAVN Beløp #INNHOLD Beløp postert denne periode inkludert etterbetalinger';
comment on column dvh_fam_bt.fak_bt_mottaker.belophie is '#NAVN BeløpEtterbetaltHittil #INNHOLD Beløp etterbetalt hittil i år. Utbetalinger som ikke er for inneværende periode';
comment on column dvh_fam_bt.fak_bt_mottaker.sambo is '#NAVN Samboerskap #INNHOLD Samboerskap. Kun fra Infotrygd. Verdier B,F,S på få rader';
comment on column dvh_fam_bt.fak_bt_mottaker.prosent is '#NAVN Delingsprosent #INNHOLD Delingsprosent ytelse, verdi 0 (100 %) eller 50';
comment on column dvh_fam_bt.fak_bt_mottaker.eokland is '#NAVN KompententLand #INNHOLD Kompentent land for EØS sak';
comment on column dvh_fam_bt.fak_bt_mottaker.eodland is '#NAVN DifferanseLand #INNHOLD Differanse land for EØS sak';
comment on column dvh_fam_bt.fak_bt_mottaker.eoybland is '#NAVN YngsteBarnsBostedland #INNHOLD Yngste barns bostedland for EØS sak';
comment on column dvh_fam_bt.fak_bt_mottaker.eopens is '#NAVN #INNHOLD Ikke i bruk';
comment on column dvh_fam_bt.fak_bt_mottaker.eoobland is '#NAVN ØvrigeBarnsBostedland #INNHOLD Øvrige barns bostedland for EØS sak';
comment on column dvh_fam_bt.fak_bt_mottaker.eomornas is '#NAVN MorsNasjonalitet #INNHOLD Mors nasjonalitet for aktuell eøs sak';
comment on column dvh_fam_bt.fak_bt_mottaker.eofarnas is '#NAVN FarsNasjonalitet #INNHOLD Fars nasjonalitet for aktuell eøs sak';
comment on column dvh_fam_bt.fak_bt_mottaker.eoybnas is '#NAVN YngsteBarnsNasjonalitet #INNHOLD Yngste barns nasjonalitet';
comment on column dvh_fam_bt.fak_bt_mottaker.tknr is '#NAVN KommuneNR #INNHOLD Kommunenummer';
comment on column dvh_fam_bt.fak_bt_mottaker.belophit is '#NAVN AkkumulertBeløp #INNHOLD Akkumulert beløp utbetalt hittil i år';
comment on column dvh_fam_bt.fak_bt_mottaker.statusk is '#NAVN Status #INNHOLD Status, 0=manuell beregning, 1=ordinær stønad, 2=Enslig forsørger, 3=Omsorg for sykt barn, 4=Barn anbrakt institusjon';
comment on column dvh_fam_bt.fak_bt_mottaker.antbarn is '#NAVN AntallBarn #INNHOLD Antall barn';
comment on column dvh_fam_bt.fak_bt_mottaker.antbarnh is '#NAVN AntallBarnHjemmeboende #INNHOLD Antall barn hjemmeboende. Ikke fra ny vedtaksløning';
comment on column dvh_fam_bt.fak_bt_mottaker.ybarn is '#NAVN YngsteBarnAlder #INNHOLD Alder på yngste barn';
comment on column dvh_fam_bt.fak_bt_mottaker.kjonn is '#NAVN Kjønn #INNHOLD Mottakerens kjønn';
comment on column dvh_fam_bt.fak_bt_mottaker.fodsel_aar is '#NAVN Fødselsår #INNHOLD Fødselsår for mottakeren';
comment on column dvh_fam_bt.fak_bt_mottaker.stat_aarmnd is '#NAVN StatistikkMåned #INNHOLD Statistikk måned YYYYMM';
comment on column dvh_fam_bt.fak_bt_mottaker.fodsel_mnd is '#NAVN Fødselsmåned #INNHOLD Fødselsmåned for mottakeren';
comment on column dvh_fam_bt.fak_bt_mottaker.kilde is '#NAVN Kilde #INNHOLD Kildesystem BT (Vedtaksløsning/UR) eller Infotrygd';
comment on column dvh_fam_bt.fak_bt_mottaker.bosted_kommune_nr is '#NAVN BostedskommuneNr #INNHOLD Bostedskommune nr for mottaker';
comment on column dvh_fam_bt.fak_bt_mottaker.bosted_bydel_kommune_nr is '#NAVN Bosted/bydelNR #INNHOLD Bosted/bydel nr for mottaker';
comment on column dvh_fam_bt.fak_bt_mottaker.navarende_kommune_nr is '#NAVN NåværendeKommuneNR #INNHOLD Nåværende kommunenummer for mottaker';
comment on column dvh_fam_bt.fak_bt_mottaker.fagsak_id is '#NAVN FagsakId #INNHOLD FAGSAK_ID fra kildesystem';
comment on column dvh_fam_bt.fak_bt_mottaker.belop_utvidet is '#NAVN BeløpUtvidet #INNHOLD Utbetalt beløp for utvidet barnetrygd postert denne periode, inkludert etterbetalinger';
comment on column dvh_fam_bt.fak_bt_mottaker.belophit_utvidet is '#NAVN BeløpUtvidetHittil #INNHOLD Beløp utbetalt hittil i år for utvidet barnetrygd';
comment on column dvh_fam_bt.fak_bt_mottaker.belop_smabarnstillegg is '#NAVN Småbarnstillegg #INNHOLD Småbarnstillegg';
comment on column dvh_fam_bt.fak_bt_mottaker.belop_finnmark is '#NAVN Finnmarkstillegg #INNHOLD Finnmarkstillegg';
comment on column dvh_fam_bt.fak_bt_mottaker.belop_svalbard is '#NAVN Svalbardstillegg #INNHOLD Svalbardstillegg';
comment on column dvh_fam_bt.fak_bt_mottaker.belope is '#NAVN BeløpEtterbetalt #INNHOLD Beløp etterbetalt for tidligere perioder og utbetalt denne periode';
comment on column dvh_fam_bt.fak_bt_mottaker.dim_gt_verdi is '#NAVN GTVerdi #INNHOLD Geografisk tilknytning';
comment on column dvh_fam_bt.fak_bt_mottaker.dim_getitype is '#NAVN GetiType #INNHOLD kommune, bydel, utland eller, udefinert';
comment on column dvh_fam_bt.fak_bt_mottaker.sokersaktivitet is '#NAVN SøkersAktivitet #INNHOLD Søkers aktivitet - EØS';
comment on column dvh_fam_bt.fak_bt_mottaker.annenforelder_aktivitet is '#NAVN AnnenForeldersAktivitet #INNHOLD Annen forelders aktivitet- EØS';
comment on column dvh_fam_bt.fak_bt_mottaker.kompetanse_resultat is '#NAVN EØS resultat #INNHOLD Kompetanse resultat - EØS';
comment on column dvh_fam_bt.fak_bt_mottaker.barnets_bostedsland is '#NAVN BarnetsBostedland #INNHOLD Barnets bostedslannd -EØS';
comment on column dvh_fam_bt.fak_bt_mottaker.mottaker_bosted_land is '#NAVN MottakersBostedland #INNHOLD Mottakers bostedsland';
comment on column dvh_fam_bt.fak_bt_mottaker.fk_dim_person is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til DIM_DIM for mottaker';
comment on column dvh_fam_bt.fak_bt_mottaker.fk_dim_alder is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til DIM_ALDER for mottaker';
comment on column dvh_fam_bt.fak_bt_mottaker.fk_dim_kjonn is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til DIM_KJONN for mottaker';
comment on column dvh_fam_bt.fak_bt_mottaker.fk_dim_land_fodt is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til DIM_LAND for mottaker/fødeland';
comment on column dvh_fam_bt.fak_bt_mottaker.fk_dim_tid_mnd is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til DIM_TID for statistikkperiode (STAT_AARMND)';
comment on column dvh_fam_bt.fak_bt_mottaker.fk_dim_geografi_bosted is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til DIM_GEOGRAFI for bostedsinformasjon';