comment on table dvh_fam_bt.fam_bt_fagsak is '#NAVN Fagsak #INNHOLD Tabellen inneholder barnetrygd vedtaksinformasjon.';
comment on column dvh_fam_bt.fam_bt_fagsak.pk_bt_fagsak is '#NAVN Primær nøkkel #INNHOLD Primær nøkkel, en unik id for hver rad (vedtak), autogenerert av dvh_fambt_kafka.hibernate_sequence.nextval.';
comment on column dvh_fam_bt.fam_bt_fagsak.fk_bt_person is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til FAM_BT_PERSON.';
comment on column dvh_fam_bt.fam_bt_fagsak.fk_bt_meta_data is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til FAM_BT_META_DATA.';
comment on column dvh_fam_bt.fam_bt_fagsak.fagsak_id is '#NAVN FagsakId #INNHOLD Barnetrygd fagsak_id fra vedtaksystem.';
comment on column dvh_fam_bt.fam_bt_fagsak.behandlings_id is '#NAVN BehandlingsId #INNHOLD Barnetrygd behandlings_id fra vedtaksystem. Kan identifisere versjon av fagsak.';
comment on column dvh_fam_bt.fam_bt_fagsak.tidspunkt_vedtak is '#NAVN Vedtaks tidspunkt #INNHOLD Tidspunkt for når vedtaket er fattet.';
comment on column dvh_fam_bt.fam_bt_fagsak.enslig_forsørger is '#NAVN Enslig forsørger #INNHOLD Info om mottaker er enslig forsørger. Boolean.';
comment on column dvh_fam_bt.fam_bt_fagsak.kafka_offset is '#NAVN KafkaOffset #INNHOLD Kafka offset av kafka topic-en hvor jsonmelding til vedtaket kommer fra.';
comment on column dvh_fam_bt.fam_bt_fagsak.kildesystem is '#NAVN Kildesystem #INNHOLD Kildesystem. BT:data ble pakket ut av DBT.';
comment on column dvh_fam_bt.fam_bt_fagsak.lastet_dato is '#NAVN Lastet dato #INNHOLD Lastet dato data ble pakket ut av DBT.';
comment on column dvh_fam_bt.fam_bt_fagsak.kafka_mottatt_dato is '#NAVN Kafka mottatt dato #INNHOLD Tidspunkt til når vedtaket er kommet på kafka_topic-en.';
comment on column dvh_fam_bt.fam_bt_fagsak.behandling_opprinnelse is '#NAVN Behandlings opprinnelse #INNHOLD Fra vedtak og kan være NULL, MANUELL eller AUTOMATISK_VED_FØDSELSHENDELSE.';
comment on column dvh_fam_bt.fam_bt_fagsak.behandling_type is '#NAVN Behandlings type #INNHOLD Fra vedtak og kan være FØRSTEGANGSBEHANDLING, REVURDERING, MIGRERING_FRA_INFOTRYGD, TEKNISK_ENDRING eller TEKNISK_OPPHØR.';
comment on column dvh_fam_bt.fam_bt_fagsak.funksjonell_id is '#NAVN Funksjonell Id #INNHOLD Funksjonell id fra vedtaksystem.';
comment on column dvh_fam_bt.fam_bt_fagsak.kategori is '#NAVN Kategori #INNHOLD Vedtakets kategori og det er enten NASJONAL (Norge) eller EØS.';
comment on column dvh_fam_bt.fam_bt_fagsak.underkategori is '#NAVN Underkategori #INNHOLD Mer info om vedtaket, kategorien kan deles til 2 underkategori ORDINÆR (ordinær barnetrygd) eller UTVIDET (utvidet barnetrygd).';
comment on column dvh_fam_bt.fam_bt_fagsak.behandling_årsak is '#NAVN Behandlings årsak #INNHOLD Årsaken til behandling av vedtaket. Kan være f.eks. SATSENDRING.';
comment on column dvh_fam_bt.fam_bt_fagsak.fagsak_type is '#NAVN FagsakType #INNHOLD Type vedtak og det er enten NORMAL, BARN_ENSLIG_MINDREÅRIG, INSTITUSJON eller SKJERMET_BARN.';