comment on column dvh_fam_bt.fam_bt_mottaker.fk_person1 is '#NAVN FK_PERSON1 #INNHOLD DVH sin identifikator for FNR, mottaker av ytelsen';
comment on column dvh_fam_bt.fam_bt_mottaker.belop is '#NAVN Beløp #INNHOLD Beløp postert denne periode innkludert etterbetalinger';
comment on column dvh_fam_bt.fam_bt_mottaker.belophie is '#NAVN Beløp #INNHOLD Beløp etterbetalt hittil i år. Utbetalinger som ikke er for inneværende periode';
comment on column dvh_fam_bt.fam_bt_mottaker.sambo is '#NAVN Samboerskap #INNHOLD Samboerskap. Kun fra Infotrygd. Verdier B,F,S på få rader';
comment on column dvh_fam_bt.fam_bt_mottaker.prosent is '#NAVN Delingsprosent #INNHOLD Delingsprosent ytelse, verdi 0 (100 %) eller 50.';
comment on column dvh_fam_bt.fam_bt_mottaker.eokland is '#NAVN KompententLand #INNHOLD Kompentent land for EØS sak';
comment on column dvh_fam_bt.fam_bt_mottaker.eodland is '#NAVN DIfferanseLand #INNHOLD DIfferanse land for EØS sak';
comment on column dvh_fam_bt.fam_bt_mottaker.eoybland is '#NAVN Yngste barns bostedland #INNHOLD Yngste barns bostedland for EØS sak';
comment on column dvh_fam_bt.fam_bt_mottaker.eoobland is '#NAVN Øvrige barns bostedland #INNHOLD Øvrige barns bostedland for EØS sak';
comment on column dvh_fam_bt.fam_bt_mottaker.eomornas is '#NAVN MorsNasjonalitet #INNHOLD Mors nasjonalitet for aktuell eøs sak';
comment on column dvh_fam_bt.fam_bt_mottaker.eofarnas is '#NAVN FarsNasjonalitet #INNHOLD Fars nasjonalitet for aktuell eøs sak';
comment on column dvh_fam_bt.fam_bt_mottaker.eoybnas is '#NAVN Yngste barns nasjonalitet #INNHOLD Yngste barns nasjonalitet';
comment on column dvh_fam_bt.fam_bt_mottaker.tknr is '#NAVN TKNR #INNHOLD TKNR';
comment on column dvh_fam_bt.fam_bt_mottaker.belophit is '#NAVN AkkumulertBeløp #INNHOLD Akkumulert beløp utbetalt hittil i år';
comment on column dvh_fam_bt.fam_bt_mottaker.statusk is '#NAVN Status #INNHOLD Status, 0=manuell beregning, 1=ordinær stønad, 2=Enslig forsørger, 3=Omsorg for sykt barn, 4=Barn anbrakt institusjon';
comment on column dvh_fam_bt.fam_bt_mottaker.antbarn is '#NAVN AntallBarn #INNHOLD Antall barn';
comment on column dvh_fam_bt.fam_bt_mottaker.antbarnh is '#NAVN AntallBarnHjemmeboende #INNHOLD Antall barn hjemmeboende. Ikke fra ny vedtaksløning';
comment on column dvh_fam_bt.fam_bt_mottaker.ybarn is '#NAVN Alder #INNHOLD Alder på yngste barn';
comment on column dvh_fam_bt.fam_bt_mottaker.kjonn is '#NAVN Kjønn #INNHOLD Mottakerens kjønn';
comment on column dvh_fam_bt.fam_bt_mottaker.fodsel_aar is '#NAVN Fødselsår #INNHOLD Fødselsår for mottakeren';
comment on column dvh_fam_bt.fam_bt_mottaker.stat_aarmnd is '#NAVN StatistikkMåned #INNHOLD Statistikk måned YYYYMM';
comment on column dvh_fam_bt.fam_bt_mottaker.fodsel_mnd is '#NAVN Fødselsmåned #INNHOLD Fødselsmåned for mottakeren';
comment on column dvh_fam_bt.fam_bt_mottaker.kilde is '#NAVN Kilde #INNHOLD Kildesystem BT (Vedtaksløsning/UR) eller Infotrygd';
comment on column dvh_fam_bt.fam_bt_mottaker.lastet_dato is '#NAVN LastetDato #INNHOLD Lastet dato';
comment on column dvh_fam_bt.fam_bt_mottaker.fagsak_id is '#NAVN FagsakId #INNHOLD FAGSAK_ID id kildesystem';
comment on column dvh_fam_bt.fam_bt_mottaker.fkby_person1 is '#NAVN FK_PERSON1 #INNHOLD FK_PERSON1 for yngste barn';
comment on column dvh_fam_bt.fam_bt_mottaker.belope is '#NAVN Beløp #INNHOLD Beløp etterbetalt for tidligere perioder og utbetalt denne periode';
comment on column dvh_fam_bt.fam_bt_mottaker.fk_dim_person is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til DIM_DIM for mottaker';
comment on column dvh_fam_bt.fam_bt_mottaker.fk_dim_alder is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til DIM_ALDER for mottaker';
comment on column dvh_fam_bt.fam_bt_mottaker.fk_dim_kjonn is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til DIM_KJONN for mottaker';
comment on column dvh_fam_bt.fam_bt_mottaker.fk_dim_tid_mnd is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til DIM_TID for statistikkperiode (STAT_AARMND)';
comment on column dvh_fam_bt.fam_bt_mottaker.fk_dim_sivilstatus is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til DIM_SIVILSTATUS for mottaker/sivilstand';
comment on column dvh_fam_bt.fam_bt_mottaker.fk_dim_land_fodt is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til DIM_LAND for mottaker/fødeland';
comment on column dvh_fam_bt.fam_bt_mottaker.fk_dim_geografi_bosted is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til DIM_GEOGRAFI for bostedsinformasjon';
comment on column dvh_fam_bt.fam_bt_mottaker.fk_dim_land_statsborgerskap is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til DIM_LAND for mottaker/statsborgerskap';
comment on column dvh_fam_bt.fam_bt_mottaker.bosted_kommune_nr is '#NAVN BostedskommuneNr #INNHOLD Bostedskommune nr for mottaker';
comment on column dvh_fam_bt.fam_bt_mottaker.bosted_bydel_kommune_nr is '#NAVN Bosted/bydel nr #INNHOLD Bosted/bydel nr for mottaker';
comment on column dvh_fam_bt.fam_bt_mottaker.belop_utvidet is '#NAVN Beløp #INNHOLD Utbetalt beløp for utvidet barnetrygd postert denne periode, innkludert etterbetalinger';
comment on column dvh_fam_bt.fam_bt_mottaker.belophit_utvidet is '#NAVN Beløp #INNHOLD Beløp utbetalt hittil i år for utvidet barnetrygd';
comment on column dvh_fam_bt.fam_bt_mottaker.pk_bt_mottaker is '#NAVN Primærnøkkel #INNHOLD Primær key';
comment on column dvh_fam_bt.fam_bt_mottaker.behandling_årsak is '#NAVN BehandlingsÅrsak #INNHOLD Årsak til behandling fra Fagsystem';
comment on column dvh_fam_bt.fam_bt_mottaker.fk_bt_fagsak is '#NAVN Fremmednøkkel #INNHOLD Fremmednøkkel til FAM_BT_FAGSAK.';
comment on column dvh_fam_bt.fam_bt_mottaker.gyldig_flagg is '#NAVN GyldigFlagg #INNHOLD Gyldig flagg=1 for gyldige transaksjoner';
comment on column dvh_fam_bt.fam_bt_mottaker.mottaker_gt_verdi is '#NAVN GTVerdi #INNHOLD Geografisk tilknytning.';
comment on column dvh_fam_bt.fam_bt_mottaker.sokersaktivitet is '#NAVN SøkersAktivitet #INNHOLD Søkers aktivitet - EØS';
comment on column dvh_fam_bt.fam_bt_mottaker.annenforelder_aktivitet is '#NAVN AnnenForeldersAktivitet #INNHOLD Annen forelders aktivitet- EØS';
comment on column dvh_fam_bt.fam_bt_mottaker.kompetanse_resultat is '#NAVN EØS resultat #INNHOLD Kompetanse resultat - EØS';
comment on column dvh_fam_bt.fam_bt_mottaker.barnets_bostedsland is '#NAVN BarnetsBostedland #INNHOLD Barnets bostedslannd -EØS';
comment on column dvh_fam_bt.fam_bt_mottaker.mottaker_getitype is '#NAVN GetiType #INNHOLD kommune, bydel, utland eller, udefinert';
comment on column dvh_fam_bt.fam_bt_mottaker.mottaker_bosted_land is '#NAVN MottakersBostedland #INNHOLD Mottakers bostedsland';
comment on column dvh_fam_bt.fam_bt_mottaker.belop_smabarnstillegg is '#NAVN Beløp #INNHOLD Småbarnstillegg';

comment on table dvh_fam_bt.fam_bt_mottaker is '#NAVN FAM_BT_MOTTAKER #INNHOLD Inneholder statistikk over barnetrygd.';